### ISSUE TITLE
Incompatibility with DSMS SDK due to python dependency

### ISSUE THREAD

**Issue by yoavnash** [MI-FraunhoferIWM/data2rdf#48]
Data2rdf is at the moment incompatible with dsms-sdk since [it requires pandas==1.5.3](https://github.com/MI-FraunhoferIWM/data2rdf/blob/main/setup.cfg#L25) while the [SDK requires pandas v2](https://github.com/MI-FraunhoferIWM/dsms-python-sdk/blob/main/setup.cfg#L22).

#### Suggested solution
Pandas should not be restricted to a specific version but rather a range of versions. Supporting v2 of pandas by data2rdf is also favorable.

**Comment by lmiwm** [comment]
Here some additional information
1. I created a new conda env
2. installed data2rdf (pip install data2rdf)
3. installed dsms sdk (pip install dsms-sdk) -> got the above error, anyway, pandas 2.2.1 was installed
4. by testing data2rdf with a StahlDigital tensile test example, I got AttributeError: 'OpenpyxlWriter' object has no attribute 'save', because that method is depricated in pandas 2

**Comment by MBueschelberger** [comment]
PR #42  is supposed to solve the issue but some pytests are failling due to a problem with openpyxl.

**Comment by MBueschelberger** [comment]
Side note: data2rdf v1.0.5 and the SDK v1.1.0 are compatible with each other since we are using them in parallel in the knowledge service. PR #42 was opened in order to use the latest versions of both packages in parallel, but due to the problem with openpyxl, it wasn't finished yet.
